# Generated by Django 4.1.7 on 2023-04-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_result_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='Age',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='BMI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='Blood_Pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='D_P_Function',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='Glucose',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='Insulin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='Pregnancies',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='Skin_Thickness',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
